import ThemeRegistry from "@/theme/ThemeRegistry";
import "./globals.css";
import { Inter } from "next/font/google";
import ResponsiveAppBar from "@/components/check/NavBar/NavBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">

      <ThemeRegistry>
        <ResponsiveAppBar/>
        <body className={inter.className}>{children}</body>
      </ThemeRegistry>
    </html>
  );
}
